name: compile-test

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      # ✅ application-test.yml 복원
      - name: Restore application-test.yml
        run:
          touch ./src/main/resources/application-test.yml
          echo -e "${{ secrets.TEST_YML }}" > ./src/main/resources/application-test.yml

      # ✅ 테스트 실행 (컴파일 포함)
      - name: Run tests (includes compilation)
        run: ./gradlew test -Dspring.profiles.active=test

      # ✅ 전체 빌드 확인 (테스트 제외하고 jar 생성까지)
      - name: Build project
        run: ./gradlew build -x test
